# List all recipies
default:
    just --list

# Runs terraform get and terraform init for env
init:
    terraform get
    terraform init

# use 'terraform plan' to map out updates to apply
plan:
    amber exec -- terraform plan -out=tf.out

# use 'terraform apply' to apply updates in a 'tf.out' plan file
apply:
    terraform apply tf.out

# use 'terraform destroy' to remove all resources from AWS
destroy:
    terraform destroy

# Show output
output:
    terraform output -json

# Switch to appropriate terraform
tfswitch:
    tfswitch

# Terraform refresh
refresh:
    amber exec -- terraform refresh

# Format
fmt:
    terraform fmt

# Open application
open:
    xdg-open https://rng.prod.fpcomplete.com/public-key
	xdg-open https://game.prod.fpcomplete.com/guess-game

open-tunnel:
	zehut exec aws -- ec2-instance-connect open-tunnel --instance-id $INSTANCE_ID --remote-port 22 --local-port 3055

# Send key
send-key:
	zehut exec aws -- ec2-instance-connect send-ssh-public-key --instance-id $INSTANCE_ID --instance-os-user ubuntu --ssh-public-key file://~/.ssh/id_rsa.pub

# SSH
ssh-bastion:
	ssh -i ~/.ssh/id_rsa ubuntu@127.0.0.1 -p 3055
